package com.mosaicglobal.finance.modules.identity.domain.model;

import com.mosaicglobal.finance.shared.kernel.Ensure;

/** Stable installation identifier generated by the app on first launch. */
public record DeviceId(String value) {

  public DeviceId {
    Ensure.lengthBetween(value, 8, 128, "deviceId");
  }

  @Override
  public String toString() {
    return value;
  }
}
